version: "3"
services:
  scratch:
    build: .
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/kapitan-demo:delegated
      - ~/.ssh:/root/.ssh:delegated
      - ~/.config/gh:/root/.config/gh:delegated
      - /var/run/docker.sock:/var/run/docker-host.sock:delegated
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks: 
      - scratch
    # command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
    - HOSTPWD=${PWD}

networks:
  scratch:
    name: scratch
    # driver: bridge